# 必要数据及设置
bot_accounts: bot_accounts
default_account: default_account
host_qq: host_qq
mirai_host: http://localhost:23456
verify_key: !!str 1234567890
db_link: sqlite+aiosqlite:///data.db
api_port: 54321
api_expose: false
web_manager_api: true
web_manager_auto_boot: true
proxy: proxy
auto_upgrade: false

# 图库相关
gallery:
  setu:
    path: path
    privilege: 1
    interval: 1
    need_proxy: true
  setu18:
    path: path
    privilege: 1
    interval: 10
    default_switch: false
  real:
    path: path
    privilege: 1
    interval: 1
  real_highq:
    path: path
    privilege: 1
    interval: 1
  bizhi:
    path: path
    privilege: 1
    interval: 1
  sketch:
    path: path
    privilege: 1
    interval: 1

# 个性化设置
commands:
  default:
    prefix: []
    alias: []

# 功能相关
functions:
  tencent:
    secret_id: secret_id
    secret_key: secret_key
  saucenao_api_key: saucenao_api_key
  wolfram_alpha_key: wolfram_alpha_key
  openai_key: openai_key
  github:
    username: username
    token: token
  pica:
    username: username
    password: password
    download_cache: true
    search_cache: true
    daily_download_limit: 1
    daily_search_limit: 1
    daily_random_limit: 1
    daily_rank_limit: 1
    compress_password: i_luv_sagiri
  bilibili:
    cookie: cookie
  stable_diffusion_api: stable_diffusion_api
  lolicon:
    image_cache: true
    data_cache: true
    cache_path: cache_path
    cache18_path: cache18_path
  pdf:
    base_url: base_url
    username: username
    password: password

# 日志相关
log_related:
  error_retention: 14
  common_retention: 7

# 数据库相关
database_related:
  mysql:
    disable_pooling: false
    pool_size: 40
    max_overflow: 60